language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

env:
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=386
  - GOOS=darwin GOARCH=amd64
  - GOOS=netbsd GOARCH=386
  - GOOS=netbsd GOARCH=amd64

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go build -ldflags "-X main.version 'Travis-CI'" ./...
  - go fmt ./...
  - go vet ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
